apiVersion: tor.k8s.torproject.org/v1alpha2
kind: OnionService
metadata:
  name: nginx-torservice
  namespace: test-nginx
spec:
  version: 3
  rules:
    - port:
        number: 80
      backend:
        service:
          name: nginx-service
          port:
            number: 80
  privateKeySecret:
    name: my-full-onion-secret
